[ Input ]

# Choose between pcap and live.
inputType = "pcap"

# If inputType is pcap, indicate input files or directory(ies).
inputFiles = ["ignore-directory/data/AMF_3_1.cap"]

# If inputFile contains a directory, choose wether to follow subdirectories or not.
# Choose between 'recursive' and 'static'
inputTraversal = "recursive"


# ==================================================================================================== #


[ Middleware ]

# Choose between 'ngap' or 'nas-5gs'
protocol = "ngap"

    [ Middleware.Fuzzer ]
    # Choose between 'dumb', 'mutation', 'afl' all of these still have to be implemented
    fuzzerEngine = "dumb"

    # Seed for randomness of fuzzing engines.
    seed = 0

    # Choose which fields to fuzz (csv format). If left empty, will fuzz all fields.
    fields = "gNB-ID, procedureCode"

    # What to do if none of the fields were found.
    defaultBehavior = "fuzzwholepacket"

    [ Middleware.Multiprocessing ]

    # Maximum amount of packets kept in memory for fuzzing (maximum is 256).
    queueSize = 16

    # Amount of processor threads that will be used for fuzzing (too high a number may render the system instable).
    coreAmount = 8



# ==================================================================================================== #


[ Filter ]

# Possible behaviors: 'fuzz', 'send', 'block', 'raiseError' (stops program)
ruleSatisfiedBehaviour = "fuzz"

# If rule is not satisfied, follow behavior on packet
# Possible behaviors: 'fuzz', 'send', 'block', 'raiseError' (stops program)
defaultBehaviour = "block"

    # Apply filter on packets that satisfy expression
    [Filter.apply]
    gNB-ID = '(78, 22)'
    procedureCode = 21

    [Filter.logic] 
    expression = "gNB-ID and procedureCode"


[ Logging ]
directory = "logs"

# ==================================================================================================== #


[ OutputLevel2 ] # This is for high-confidence errors
# Choose between 'csv', 'json', or 'none' (no file output).
outputType = 'csv'
outputFilename = 'outputL2.csv'
directory = "outputs"


# ==================================================================================================== #


[ OutputLevel1 ] # This is for medium-confidence errors (requires user opinion).
# Choose between 'csv', 'json', or 'none' (no file output).
outputType = 'csv'
outputFilename = 'outputL1.csv'
directory = "outputs"